apiVersion: v1
kind: Service
metadata:  
  name: godemo-gin-service
spec:
  selector:    
    run: godemo-gin
  type: NodePort
  ports:  
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP