apiVersion: apps/v1
kind: Deployment
metadata:
  name: godemo-gin
spec:
  selector:
    matchLabels:
      run: godemo-gin
  replicas: 1
  template:
    metadata:
      labels:
        run: godemo-gin
    spec:
      containers:
        - name: godemo-gin
          image: sachs7/web-svc-gin:v1.2
          ports:
            - containerPort: 8082
          imagePullPolicy: IfNotPresent
        # Use below to run functional tests as part of service (sidecar) ----******----
        # - name: pytest-godemo-gin
        #   image: sachs7/web-svc-gin-pytest:v1.0
        #   imagePullPolicy: IfNotPresent
        # Below liveness is used for helm ----------------
        # - name: liveness
        #   image: k8s.gcr.io/busybox
        #   args:
        #   - /bin/sh
        #   - -c
        #   - touch /tmp/healthy; sleep 5; rm -rf /tmp/healthy; sleep 5
        #   livenessProbe:
        #     exec:
        #       command:
        #       - cat
        #       - /tmp/healthy
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:  
  name: godemo-gin-service
spec:
  selector:    
    run: godemo-gin
  type: NodePort
  ports:  
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
